FROM elixir

MAINTAINER Alisson Morais

RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential
RUN mix local.rebar
RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
RUN apt-get install -y inotify-tools

CMD ["iex"]
